# Generated by Django 5.0.6 on 2024-06-28 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_code', models.CharField(max_length=10, unique=True)),
                ('question_in_japanese', models.TextField()),
                ('questions_in_english', models.TextField()),
                ('possible_answers', models.TextField()),
                ('answer', models.TextField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('japanese_word', models.CharField(max_length=100)),
                ('pronunciation', models.CharField(max_length=100)),
                ('english_translation', models.CharField(max_length=100)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary', to='questions.question')),
            ],
        ),
    ]
