# Generated by Django 5.0.6 on 2024-07-05 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_alter_question_possible_answers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vocabulary',
            name='question',
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='question_code',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
